### ISSUE TITLE
Teensy LC: conflict between I2C and ADC

### ISSUE THREAD

**Issue by ChrisVeigl** [sensorium/Mozzi#139]
Using the current master branch, I got some compile error when building for the Teensy 3.2 / LC boards, in particular I had to change  lines

https://github.com/sensorium/Mozzi/blob/8df22c923f6a3040e715ab1c6abfbab587358057/MozziGuts.cpp#L399

to 

  adc->adc0->setAveraging(0);
  adc->adc0->setConversionSpeed(ADC_CONVERSION_SPEED::MED_SPEED);

to get the build done. But then, every sketch which uses the ADC hangs at mozziAnalogRead ...

I found that the hang does not happen when i prevent adc interrupts by  commenting this line:

https://github.com/sensorium/Mozzi/blob/8df22c923f6a3040e715ab1c6abfbab587358057/mozzi_analog.cpp#L74

After that, mozziAnalogRead does not provide correct ADC results, but a workaround is to create your own adc instance in the Arduino sketch, and read the adc values by e.g.

ADC *myadc = new ADC(); 
(...)
int value=myadc->adc0->analogRead(A1);

works fine in a Mozzi setup with 8 potentiometers ...

**Comment by tomcombriat** [comment]
Hei,
I put my hand on a TeensyLC. Indeed there is a problem, which actually might not be restricted to the LC. You can check #138 for the work in progress (not working, yet).

Best

**Comment by tomcombriat** [comment]
Should be solved by #138

**Comment by ChrisVeigl** [comment]
hi! thank you for having such a close look at the issue!
i can confirm that ADC initialization and readings works now on a TeensyLC, unless the I2C1 (Wire1) interface is used...
I still have problems with mozziAnalogRead() in my project, where i use I2C1 for controlling an LC display.
The code hangs when mozziAnalogRead() is called. Normal analogRead() works.

**Comment by tomcombriat** [comment]
The never ending story…

At least the ADC works when no I2C interface is used. The I2C interface is obviously on the same pins than the ADC, there might be a conflict somewhere.
I can try to see if I find the conflict (given that it is not deep down a Teensy library), I have to say that I am never using I2C on synths so that is something I did not test (I tested SPI thought).

In case you have a minimal non-working example in order for me to try to work on I would be grateful. Otherwise no big deal!
